### ISSUE TITLE
Pipeline as Code section not accessible

### ISSUE THREAD

**Issue by kmartens27** [jenkins-infra/docs.jenkins.io#10]
### Describe your use-case which is not covered by existing documentation.

It appears that the "Pipeline as Code" section is not available on the versioned Jenkins docs site. It is not available in the left navigation, and when trying to type in the `pipeline-as-code` addition to the URL, I get a 404 error page.

Would it be possible to ensure that this content is in the versioned docs site as well, or if there has been discussion about removing this, any reference to that would be great as well!

![Screenshot 2024-01-19 at 11 41 08 AM](https://github.com/jenkins-infra/docs.jenkins.io/assets/99040580/e7f1a7bb-cd8f-41ac-9010-8b4acdc2a3b8)

**Comment by Vandit1604** [comment]
Hey @kmartens27, Could you check again if the issue still persists. Thanks.

**Comment by Vandit1604** [comment]
Hey @kmartens27,
Raised #46
