### ISSUE TITLE
Fix favicon aspect ratio issue

### ISSUE THREAD

**Issue by krisstern** [jenkins-infra/docs.jenkins.io#105]
### Reproduction steps

Go to the tab of [docs.jenkins.io](https://docs.jenkins.io/) to observe the aspect ratio compared to that of https://www.jenkins.io/

### Expected Results

Favicon to look like the one in https://www.jenkins.io/

### Actual Results

Now our favicon looks kind of fat with a different favicon image

**Comment by suzitsam** [comment]
I would like to work on this.

**Comment by SufyaanKhateeb** [comment]
Is this issue taken already? @krisstern

**Comment by krisstern** [comment]
@SufyaanKhateeb Yes, according to https://github.com/jenkins-infra/docs.jenkins.io/issues/105#issuecomment-2391796679. We usually wait for any interested for 7 days for a PR until someone else may take the issue and work on it, so you should wait two more days before working on it.

**Comment by Coffemin** [comment]
It seems like 7 day has passed since @suzitsam has mentioned that he will work on this issue. Can I work on this? @krisstern

**Comment by krisstern** [comment]
Yes @Coffemin, you are more than welcome to submit a PR for this
