### ISSUE TITLE
Update the authors data under `site/authors`

### ISSUE THREAD

**Issue by Vandit1604** [jenkins-infra/docs.jenkins.io#108]
### What feature do you want to see added?

Import the author's data from https://github.com/jenkins-infra/jenkins.io/tree/master/content/_data/authors and update here under `site/authors` in the repository.

The format is different, so if we can automate this with scripting will be a huge help.

For example https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/authors/KunalSin9h.adoc and https://github.com/jenkins-infra/docs.jenkins.io/blob/main/site/authors/KunalSin9h.adoc has different formats.

**Comment by Nwaamaka-Iduwe** [comment]
Hi, I'd like to work on this!

**Comment by krisstern** [comment]
Sure, I can add that label on your PR for you later once it is accepted @Nwaamaka-Iduwe

**Comment by Nwaamaka-Iduwe** [comment]
Awesome! Thank you @krisstern

**Comment by krisstern** [comment]
You are welcome @Nwaamaka-Iduwe!
