### ISSUE TITLE
Update the supporters in the Gatsby site homepage

### ISSUE THREAD

**Issue by Vandit1604** [jenkins-infra/docs.jenkins.io#109]
### What feature do you want to see added?

Modify https://github.com/jenkins-infra/docs.jenkins.io/blob/main/site/src/components/Supporters.js to display every supporter that is currently displayed on the https://www.jenkins.io/ homepage.

![image](https://github.com/user-attachments/assets/9817d5dc-3fc1-49da-adbf-9f44c88940c4)

**Comment by Allan2000-Git** [comment]
@Vandit1604 I'd love to work on this issue.

I just have to use [this](https://github.com/jenkins-infra/docs.jenkins.io/blob/main/site/src/components/Jumbotron.js) component

**Comment by Vandit1604** [comment]
Thanks @Allan2000-Git for showing interest in this issue. Go ahead and submit a pull request for this.

**Comment by Allan2000-Git** [comment]
@Vandit1604 I've raised a PR. Please review it. Can you add `hactoberfest` & `hactoberfest-accepted` label to the issue/PR ?
