### ISSUE TITLE
Update the Jumbotron in the Gatsby site homepage

### ISSUE THREAD

**Issue by Vandit1604** [jenkins-infra/docs.jenkins.io#110]
### What feature do you want to see added?

Modify https://github.com/jenkins-infra/docs.jenkins.io/blob/main/site/src/components/Jumbotron.js to display every supporter that is currently displayed on the https://www.jenkins.io/ homepage at the end.

![image](https://github.com/user-attachments/assets/236a94f4-bef0-495a-a900-cac625f6a0d4)

**Comment by Allan2000-Git** [comment]
@Vandit1604 I'd love to work on this issue.

Confirming, the UI in the below screenshot has to be replicated in the docs right?
![Screenshot 2024-10-05 232054](https://github.com/user-attachments/assets/eb38d07b-1177-4460-989f-197f1d7279f3)

**Comment by Vandit1604** [comment]
Hi @Allan2000-Git [this](https://github.com/jenkins-infra/docs.jenkins.io/blob/main/site/src/components/Jumbotron.js) is the component you'll have to update if you are working on this issue.

You can use the SVGs from here https://github.com/jenkins-infra/jenkins.io/tree/master/content/images/sponsors

**Comment by Allan2000-Git** [comment]
That's weird. I'll use `png` as a fallback for github
