### ISSUE TITLE
Add dark mode support for versioned docs and Gatsby main site

### ISSUE THREAD

**Issue by krisstern** [jenkins-infra/docs.jenkins.io#111]
### What feature do you want to see added?

We would like to add dark mode support similar to the one introduced at https://www.jenkins.io/ recently.

**Comment by suzitsam** [comment]
I would like to work on this.

**Comment by Coffemin** [comment]
@krisstern Seems like it's been a week since suzitsam said he will work on this issue but still PR, Can I work on this issue?

**Comment by krisstern** [comment]
Hi @Coffemin Sure, you may work on this

**Comment by krisstern** [comment]
Also @Coffemin this may take more than 7 days, if that is the case just let us know here that you may need more time

**Comment by Coffemin** [comment]
Okay! Got it! @krisstern

**Comment by Coffemin** [comment]
I'm currently working on this and need more time.

**Comment by krisstern** [comment]
HI @Coffemin,

Sure! Also, you may use the following merged PR's as references:

1. Add dark mode: https://github.com/jenkins-infra/jenkins.io/pull/7266
2. Fix some elements in dark mode: https://github.com/jenkins-infra/jenkins.io/pull/7457
3. Update back link icon in dark mode: https://github.com/jenkins-infra/jenkins.io/pull/7458
4. Refresh the design of the 'Changelogs' pages: https://github.com/jenkins-infra/jenkins.io/pull/7479

**Comment by Coffemin** [comment]
@krisstern,

I’ve noticed an issue when trying to add dark mode within the :root selector using @media screen and (prefers-color-scheme: dark), as done in [this PR](https://github.com/jenkins-infra/jenkins.io/pull/7266). The dark theme colors are not displaying as expected.

However, when I apply the dark theme colors directly within specific element selectors (e.g., body, a, etc.), the dark theme displays correctly. While adding dark mode support through individual element selectors seems like a viable solution, it could make future changes more complex.

Could you please confirm if I should continue exploring the :root selector approach for easier debugging and future adjustments, or proceed with implementing dark mode directly within element selectors?

**Comment by krisstern** [comment]
Hi @Coffemin,

If you are trying to add dark mode to the Antora site I would suggest doing so at https://github.com/jenkins-infra/docs.jenkins.io/blob/main/ui/src/css/base.css using something like

```css
@media screen and (prefers-color-scheme: dark) {
    .class {
        ...
    }
}
```

Since I don't think we have an existing class name called `root` so maybe use classnames that are already in existence or feel free to create new ones if there is a need to.

**Comment by krisstern** [comment]
But if you mean you would like to change the existing `:root` setting you can change it here: https://github.com/jenkins-infra/docs.jenkins.io/blob/main/ui/src/css/vars.css
