### ISSUE TITLE
Update the documentation at "README.adoc"

### ISSUE THREAD

**Issue by krisstern** [jenkins-infra/docs.jenkins.io#121]
### Describe your use-case which is not covered by existing documentation.

The current documentation we have at https://github.com/jenkins-infra/docs.jenkins.io/blob/main/README.adoc is simply a stub, and needs reworking to provide more info such as the separation of the versioned controlled Antora part and the non-versioned controlled Gatsby part, where the latter is a basis of the to-be-replaced https://jenkins.io/ website. 

Also, we could add some link to the existing Gatsby "README.md" at https://github.com/jenkins-infra/docs.jenkins.io/tree/main/site#readme.

**Comment by Brijeshthummar02** [comment]
hey there, @krisstern i can work on this, assign me.

**Comment by krisstern** [comment]
Hi @Brijeshthummar02,
Thanks for your interest in contributing! We do not normally assign issues, but you may work on this. Please keep us posted of any progress here in this thread. If we do not hear from you after 7 days, we will release the issue to be worked on by someone else interested.

**Comment by Brijeshthummar02** [comment]
@krisstern pr is on, go through it.
