### ISSUE TITLE
Add CONTRIBUTING guide to repo following practice at jenkins-infra/jenkins.io repo

### ISSUE THREAD

**Issue by krisstern** [jenkins-infra/docs.jenkins.io#122]
### Describe your use-case which is not covered by existing documentation.

As we will be replacing the existing https://www.jenkins.io/ website with the docs in this repo, we would like to add a similar "CONTRIBUTING.adoc" file serving as a guide for future contributions as currently exists at https://github.com/jenkins-infra/jenkins.io/blob/master/CONTRIBUTING.adoc. 

Please note that some copy-editing and modifications may be needed to complete the task to satisfaction.

**Comment by adripo** [comment]
Hi, I would like to work on this issue

**Comment by krisstern** [comment]
Hey sure @adripo! Keep us posted here on any progress. If we do not hear back from you within the next 7 days we will open up the issue to someone else interesd in working on it.

**Comment by adripo** [comment]
@krisstern Hi, I have created the CONTRIBUTING.adoc file based on the guidelines from [jenkins.io](https://github.com/jenkins-infra/jenkins.io/blob/master/CONTRIBUTING.adoc), making necessary adjustments for our project.

This serves as a solid starting point for contributors and can be expanded in the future to include more details on adding or editing content.

Let me know if you have any feedback.
