### ISSUE TITLE
Update the documentation at site/ for the Gatsby-based jenkins.io website

### ISSUE THREAD

**Issue by krisstern** [jenkins-infra/docs.jenkins.io#123]
### Describe your use-case which is not covered by existing documentation.

We currently have a stub as a documentation at https://github.com/jenkins-infra/docs.jenkins.io/blob/main/site/README.md which we will need to either update/add details, which should include (but not necessarily limited to) the following:

1. Change the startup command at [#running-the-project](https://github.com/jenkins-infra/docs.jenkins.io/blob/main/site/README.md#running-the-project) to :
```console
npm run clean && npm run develop
```

2. Add details about which folders are supposed to be generated by running the above command afresh and should be ignored with a ".gitignore" file. 

3. Link up this doc with the [README.adoc at root](https://github.com/jenkins-infra/docs.jenkins.io/blob/main/README.adoc)

4. Add any other details that may be relevant for the Gatsby site. (Open to suggestions!)

**Comment by Nwaamaka-Iduwe** [comment]
Hi, I'd like to work on this.

**Comment by Ashish-CodeJourney** [comment]
can you assign it to me ?

**Comment by krisstern** [comment]
Hi @Nwaamaka-Iduwe Yes, you may work on this and post your progress here. If we do not here from you either here in this thread or receive a PR from you after 7 days, the issue will be released to someone else interested in this issue.

**Comment by krisstern** [comment]
@Ashish-CodeJourney No, someone else asked before you did.

**Comment by Nwaamaka-Iduwe** [comment]
> Hi @Nwaamaka-Iduwe Yes, you may work on this and post your progress here. If we do not here from you either here in this thread or receive a PR from you after 7 days, the issue will be released to someone else interested in this issue.

Thanks, noted.

**Comment by Nwaamaka-Iduwe** [comment]
Hi @krisstern I've now made a pull request. Thanks!
