### ISSUE TITLE
Update "Projects" > "Suggest a presentation" page UI

### ISSUE THREAD

**Issue by krisstern** [jenkins-infra/docs.jenkins.io#136]
### What feature do you want to see added?

Currently the spacing of the navigation bar on the left hand side of the UI of the "Projects" > "Suggest a presentation" page seems inconsistent with the rest of the versioned docs. Also, the contact form on the right hand side needs a bit of dressing up:

<img width="1410" alt="Screenshot 2024-10-13 at 12 21 52 AM" src="https://github.com/user-attachments/assets/75c63cf7-e788-4aa8-8583-61222961d245">

We would like to update the UI of this page to make it more visually pleasing and consistent with the rest. 

### Upstream changes

N/A

**Comment by pateldivyesh1323** [comment]
@krisstern I would like to work on this.

**Comment by krisstern** [comment]
Sure @pateldivyesh1323, thanks for your interest in this! You may start work on the issue. Please keep us posted here on any progress or submit a PR over the next 7 days. If we do not hear back from you after 7 days, we would release this issue to another interested contributor.

**Comment by Ashish-CodeJourney** [comment]
can you assign it to me ?

**Comment by krisstern** [comment]
@Ashish-CodeJourney No, @pateldivyesh1323 is working on this. You will need to wait after 7 days since my confirmation to ask again.
