### ISSUE TITLE
Stray `]` symbols immediately preceding YouTube videos on User Documentation > Blue Ocean page

### ISSUE THREAD

**Issue by krisstern** [jenkins-infra/docs.jenkins.io#156]
### Reproduction steps

Would like to have the stray `]` symbols removed from the page:

<img width="1438" alt="Screenshot 2024-10-18 at 2 43 08 AM" src="https://github.com/user-attachments/assets/43b9fb25-cf46-4ead-979b-186fd26df917">

<img width="1437" alt="Screenshot 2024-10-18 at 2 45 26 AM" src="https://github.com/user-attachments/assets/f886dca8-43fa-4c4e-ac59-9923fe749a49">

### Expected Results

No stray `]` shown

### Actual Results

Stay `]` shown

### Anything else?

N/A

**Comment by Coffemin** [comment]
@krisstern Can I work on this?

**Comment by krisstern** [comment]
Sure @Coffemin
