### ISSUE TITLE
Add dark mode support for Gatsby site

### ISSUE THREAD

**Issue by krisstern** [jenkins-infra/docs.jenkins.io#185]
### What feature do you want to see added?

To add dark mode support to Gatsby site like what we have done for https://www.jenkins.io/. 

### Upstream changes

N/A

**Comment by saurabhraghuvanshii** [comment]
Hii @krisstern I can work on this .

**Comment by krisstern** [comment]
Sure @saurabhraghuvanshii

**Comment by krisstern** [comment]
Also, you may use the following merged PR's as references:

1. Add dark mode: https://github.com/jenkins-infra/jenkins.io/pull/7266
2. Fix some elements in dark mode: https://github.com/jenkins-infra/jenkins.io/pull/7457
3. Update back link icon in dark mode: https://github.com/jenkins-infra/jenkins.io/pull/7458
4. Refresh the design of the 'Changelogs' pages: https://github.com/jenkins-infra/jenkins.io/pull/7479

**Comment by saurabhraghuvanshii** [comment]
@krisstern ok sir

**Comment by saurabhraghuvanshii** [comment]
Hii @krisstern  I have two question , that the changes where I have do is in docs.jenkins.io-gs/site .
![Screenshot 2024-11-30 185737](https://github.com/user-attachments/assets/ad6e63cf-e416-4786-9351-744fbbda8839)
And as I see that site is not responsive .

**Comment by krisstern** [comment]
Hi @saurabhraghuvanshii yes, the changes you will need to do are to `docs.jenkins.io-gs/site`. 

However, even if the site is not responsive, it should not affect your ability to implement dark mode or not, or does it? Hence I don't understand what you are asking.

**Comment by saurabhraghuvanshii** [comment]
@krisstern no I does not affect to implement dark mode , I just asking .

**Comment by krisstern** [comment]
Thanks for confirming!
