### ISSUE TITLE
Links do not lead to Download page

### ISSUE THREAD

**Issue by kmartens27** [jenkins-infra/docs.jenkins.io#4]
### Describe your use-case which is not covered by existing documentation.

In the current jenkins.io site, there are several links throughout that navigate the user to the [Download](https://www.jenkins.io/download/) page. However, in the versioned docs site, this page is not linked to correctly, and either [does not process/display](http://127.0.0.1:8081/download), or it leads to the screen shown in the screen shot.

Is the download page something that will be migrated as well, or is this something that will be left on jenkins.io? If it will be left on jenkins.io, can the links that lead to the download page navigate properly?
![Screenshot 2024-01-18 at 4 44 10 PM](https://github.com/jenkins-infra/docs.jenkins.io/assets/99040580/7893a11a-b457-4370-976c-97ccfddb0e60)

**Comment by Vandit1604** [comment]
The Download Page is made with Gatsby which is currently not added to this repo. @krisstern can elaborate more How gatsby site pages will be handled later.

**Comment by Vandit1604** [comment]
The Download Page is made with Gatsby which is currently not added to this repo that's why they are not working. @krisstern  can elaborate more How gatsby site pages will be handled.

**Comment by kmartens27** [comment]
No worries at all @Vandit1604, I was able to discuss with @MarkEWaite further and that was one of the possibilities that we came to, so that makes sense!. No worries at all, I just wanted to make sure it was brought to your attention in case it was something else!

**Comment by kmartens27** [comment]
Would the Pipeline Steps reference and Pipeline Examples pages fall under the same idea?

**Comment by Vandit1604** [comment]
Yes, Since the Pipeline Steps Reference need to have the search bar functionality. It would be easier to implement both of that in Gatsby.

**Comment by kmartens27** [comment]
Thanks for explaining @Vandit1604, that makes total sense to me and I'm okay with closing the issue in that case.

**Comment by krisstern** [comment]
> The Download Page is made with Gatsby which is currently not added to this repo that's why they are not working. @krisstern can elaborate more How gatsby site pages will be handled.

Hi @Vandit1604, can you not just link not to the same repo but to the permalink at jenkins.io? We have been doing this for the other links that are set up similarly. I thought you know or should know.

**Comment by Vandit1604** [comment]
Submitted this PR https://github.com/jenkins-infra/docs.jenkins.io/pull/12

For those pages that are not hosted yet, Links will direct to [jenkins.io](https://www.jenkins.io/)
