### ISSUE TITLE
Blue ocean root page doesn't exist on the sidebar nav dropdown.

### ISSUE THREAD

**Issue by Vandit1604** [jenkins-infra/docs.jenkins.io#62]
### Describe your use-case which is not covered by existing documentation.

On https://docs.jenkins.io/projects/blueocean/about.html, on the sidebar we can see `index.adoc` for the dropdown linking pages related to blue ocean. Since we only have `about.adoc` and `contributing.adoc` as the available pages on the subject of Blue Ocean subproject information. I suggest using `about.adoc` as the dropdown text and `contributing.adoc` can live under it or link https://docs.jenkins.io/user-docs/2.426.x/blueocean/index.html as the `index.adoc` page whichever option seems right or if anyone has other thoughts about this we can work from there.

![image](https://github.com/jenkins-infra/docs.jenkins.io/assets/107131545/d93d8bc6-004e-44cc-9d6f-53e36b0e348d)

**Comment by etorres07** [comment]
Working on this!

**Comment by krisstern** [comment]
Thanks @etorres07!
