### ISSUE TITLE
Working with projects section not linked in navigation

### ISSUE THREAD

**Issue by kmartens27** [jenkins-infra/docs.jenkins.io#8]
### Describe your use-case which is not covered by existing documentation.

Similar to https://github.com/jenkins-infra/docs.jenkins.io/issues/7, the "Working with projects" section is missing from the navigation under Using Jenkins on the versioned docs site.

Currently, on Jenkins.io, the Working with projects section is linked directly below the Best Practices section.

As previously, I can add `working-with-projects` to the URL and navigate to the page, but it is not easily found in the left navigation pane.

![Screenshot 2024-01-19 at 11 09 40 AM](https://github.com/jenkins-infra/docs.jenkins.io/assets/99040580/0a7053e0-d3e0-4931-a781-214c31af5ea7)

**Comment by Vandit1604** [comment]
Hey @kmartens27 Can you check if this issue still persists as the linked PR is merged addressing the issue. If it's not solved yet. I'll start working on it.

**Comment by kmartens27** [comment]
Hi @Vandit1604, it does appear that the Best Practices page is now linked when I run the fork locally. Thanks for checking in on this!
![Screenshot 2024-02-08 at 3 53 39 PM](https://github.com/jenkins-infra/docs.jenkins.io/assets/99040580/e228ca6e-f301-4f7f-b8ec-dfdab5b2f566)

**Comment by Vandit1604** [comment]
Thanks for closing this @kmartens27
In your own time can you check #9 and #10 I have addressed them to.
if any more changes, please let me know.
Thank you for your time.
